export const theme = {
  colors: {
    primary: '#6C3CE1',
    primaryLight: '#8B5CF6',
    primaryDark: '#5528C8',
    primaryGradientStart: '#6C3CE1',
    primaryGradientEnd: '#8B5CF6',
    primarySurface: '#F0EBFF',
    background: '#F8F7FC',
    surface: '#FFFFFF',
    text: '#1A1A2E',
    textSecondary: '#6B7280',
    textMuted: '#9CA3AF',
    border: '#E5E7EB',
    borderLight: '#F3F4F6',
  font: {
    regular: 'Inter_400Regular',
    medium: 'Inter_500Medium',
    semiBold: 'Inter_600SemiBold',
    bold: 'Inter_700Bold',
    extraBold: 'Inter_800ExtraBold',
  },
    success: '#22C55E',
    successSurface: '#F0FDF4',
    warning: '#F59E0B',
    warningSurface: '#FFFBEB',
    danger: '#EF4444',
    dangerSurface: '#FEF2F2',
    info: '#3B82F6',
    infoSurface: '#EFF6FF',
  },
  spacing: { xs: 4, sm: 8, md: 12, lg: 16, xl: 24, xxl: 32 },
  borderRadius: { sm: 6, md: 10, lg: 12, xl: 16, full: 9999 },
  shadow: {
    sm: { shadowColor: '#6C3CE1', shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.04, shadowRadius: 4, elevation: 1 },
    md: { shadowColor: '#6C3CE1', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.06, shadowRadius: 8, elevation: 2 },
    lg: { shadowColor: '#6C3CE1', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.1, shadowRadius: 12, elevation: 4 },
    fab: { shadowColor: '#6C3CE1', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.3, shadowRadius: 8, elevation: 6 },
  },
  typography: {
    pageTitle: { fontFamily: 'Inter_800ExtraBold', fontSize: 28, fontWeight: '800' as const, color: '#1A1A2E' },
    sectionTitle: { fontFamily: 'Inter_700Bold', fontSize: 16, fontWeight: '700' as const, color: '#1A1A2E' },
    body: { fontFamily: 'Inter_400Regular', fontSize: 14, fontWeight: '400' as const, color: '#1A1A2E' },
    label: { fontFamily: 'Inter_500Medium', fontSize: 12, fontWeight: '500' as const, color: '#6B7280' },
    statLarge: { fontFamily: 'Inter_800ExtraBold', fontSize: 28, fontWeight: '800' as const, color: '#1A1A2E' },
    badge: { fontFamily: 'Inter_600SemiBold', fontSize: 11, fontWeight: '600' as const },
  },
};
